### ISSUE TITLE
Error message when importing GO genesets

### ISSUE THREAD

**Issue by Ju-Rien** [lgeistlinger/EnrichmentBrowser#1]
I ran the following code lines to get started with EnrichmentBrowser and import GO biological process gene sets, but get the shown error messages. I tried to troubleshoot, but can't make it work. I work on R v3.4.3.
```
>gs_go <- get.go.genesets(org = "hsa", onto ="BP", mode = "GO.db")
 Error in initialize(value, ...) : 
  argument "go_id" is missing, with no default 
>
> gs_go <- get.go.genesets(org = "hsa", onto ="BP", mode = "biomart")
Error in if (is.na(match(dataset, validDatasets$dataset))) stop(paste("The given dataset: ",  : 
  argument is of length zero
```

I primarily write it out so the issue can be fixed, but if anyone has a workaround for now, I'd like to check it out!

**Comment by lgeistlinger** [comment]
Thanks for reporting this.
Can you update to R-3.5.0 and the new Bioconductor release 3.7 along with the corresponding EnrichmentBrowser release version 2.10.1 and let me know whether the error persists?

**Comment by Ju-Rien** [comment]
Yes, this fixes the problem. Thank you for the help!
