### ISSUE TITLE
Already have DE gene lists

### ISSUE THREAD

**Issue by fcamus** [lgeistlinger/EnrichmentBrowser#15]
Hi there, 

I was reading through the vignette and was wondering if I have to do all the differential gene analysis if I already have a list of DE genes (with FC and FDR values)? 

I am basically comparing gene expression changes using D.melanogaster under two different diet conditions. All my analyse shave been done using EdgeR. 

thanks!

**Comment by lgeistlinger** [comment]
It's ok to go from there.
Just create the `SummarizedExperiment` and annotate the required information incl your DE measures to it. See the `?sbea`, argument `se` for required annotations, and don't hesitate to report back if things are unclear.

**Comment by fcamus** [comment]
Thanks for the post. to be honest I am having a real hard time turning my experiment to a SummarizedExperiment file. I've never worked with it before. Sorry for the hassle!

**Comment by lgeistlinger** [comment]
Can the function `readSE` help?
