### ISSUE TITLE
Including batch effect correction

### ISSUE THREAD

**Issue by ktmf1991** [lgeistlinger/EnrichmentBrowser#16]
Hi,

I am trying to use the data I have with sva correction. However `deAna() `doesn't provide that option so I will need to create a SummarizedExperiment object. Since I am using voom+limma for DGE analysis and sva for batch effect correction, should I use the expression from the output of voom+limma+sva or the original normalised count data? I notice there is a `.detectDataType()` in-built function. By the function my data, if I use the voom+limma+sva output, will be classified as microarray. Will there be any effect to the analysis?

And just a minor suggestion. If deAna() includes an argument that can modify the design of the experiment that will be great.

Many thanks.

**Comment by lgeistlinger** [comment]
I believe you did something like:
```
svobj <- sva(edata, mod)
modSv <- cbind(mod, svobj$sv)
```
and then
```
res <- voom(edata, modSv)
```
and now you want to continue with enrichment analysis eg with `sbea`?

**Comment by ktmf1991** [comment]
Thank you for your prompt response! Yes. That's basically what I want to do after the voom transformation. I am also not sure if it is compatible with GSEA since the original GSEA script did something like +0.000001, which looks like something to avoid zero value?

And if I want to use the methods in `sbea` which takes only RNA-Seq normalised counts, how should I include the batch effect correction variables in the input?

**Comment by lgeistlinger** [comment]
I think there are several ways to go here.
Probably the easiest way is:
1. `voom`-transform the raw RNA-seq read counts to satisfy a microarray-like distribution
2. Input the resulting (from `voom`) expression matrix `E` containing normalized expression values on the log2 scale to `sva::ComBat`
3. Use the resulting (from `sva::ComBat`) expression matrix containing batch-effect adjusted expression values as input for your `EnrichmentBrowser` function of choice such as `deAna` or `sbea`.

This assumes that your experimental design doesn't go beyond binary grouping and optionally paired/blocked samples.

**Comment by ktmf1991** [comment]
Thanks! I just compared the results of deAna as you suggested and just using voom. They don't match exactly, probably because I chose when I am running the `eBayes()` function I chose `robust = T`. So after spending some time to read through the vignette again I build the results I have into a `SummarizedExperiment` object.

I am still a little bit concern about what the data type in the metadata would do to the analysis, other than restricting the method that can be chosen, e.g. accessing the wrong/inappropriate method for the data if I set it wrongly. Should I make it "ma" or "rseq", since it is RNA-Seq data now transformed into microarray-like distribution? And is the same restriction applied to `nbea`? 

Sorry for being a bit annoying. I just want to make sure that I am not applying the wrong method and end up getting wrong results.

In addition I just tried `eaBrowse()` but an error message popped up
```
> sbea.res <- sbea(method="gsea", se=se_ma, gs=kegg.gs)
Permutations: 1 -- 100
Permutations: 101 -- 200
Permutations: 201 -- 300
Permutations: 301 -- 400
Permutations: 401 -- 500
Permutations: 501 -- 600
Permutations: 601 -- 700
Permutations: 701 -- 800
Permutations: 801 -- 900
Permutations: 901 -- 1000
Processing ...
> eaBrowse(sbea.res)
Creating gene report ...
Error in round(fcs[, 1], digits = 2) : 
  non-numeric argument to mathematical function
```
Can it be due to incorrect input? But the GSEA seems to be running alright.

**Comment by lgeistlinger** [comment]
As for the error: what does 
```
summary(rowData(se_ma)$FC)
```
give?

**Comment by lgeistlinger** [comment]
As for your concern:

once you input voom-transformed data (log2 normalized counts), `EnrichmentBrowser` functions will detect this as `ma` (microarray), which is exactly what you want in this case.

**Comment by ktmf1991** [comment]
I see what happened. I wrote the results out in a .tab file before doing `readSE()` and it turned into character instead of numeric. Thank you for helping!
