### ISSUE TITLE
Error catching with new import function.

### ISSUE THREAD

**Issue by ghost** [lgeistlinger/EnrichmentBrowser#25]
I think the following line:
https://github.com/lgeistlinger/EnrichmentBrowser/blob/4357b8004cdcd70093ec69b5b1448bd019fad77c/R/import.R#L155
...should use `%in%` instead of `==`, because there are issues if the ordering is different.  

I get the following error when the data is not in the same order:
```
Error in EnrichmentBrowser::import(dgel.voom, ebayes_table,  : 
  all(rownames(obj) == rownames(res)) is not TRUE
```

**Comment by lgeistlinger** [comment]
The current implementation expects the result table to have the same number of rows as the expression matrix, and also that the order of the rows is the same / consistent:

```
res <- topTable(fit, coef = 2, number = nrow(counts), sort.by = "none")
```

Which steps could result in an ordering that is not consistent between expression matrix and DE table?
That said, we could of course reorder things (something convenient for the user) to ensure consistency between expression matrix and DE table.

**Comment by ghost** [comment]
I'm just going to throw some ideas around..

If you set `sort.by` to anything other than "none" it will be in a different order.  By default all of the `limma::topT*()` functions have the `sort.by` set.  With this in mind...

# 1
I think that the `import` function either needs to have error handling for the order of the rows, or `import` should re-order the rows under the hood.

# 2
There are other options too.  For limma input results (`res`) you could require an `MArrayLM` object from `limma::eBayes` or `limma::treat`.  And then use `toptable(..., sort.by="none")` under the hood.

Alternatively, if you keep the type requirements the same for limma results (topTable dataframe), then it also might be worth it to consider a filter step if the expression matrix has more rows than the results matrix.

**Comment by lgeistlinger** [comment]
This is now possible (fc25fd4).

1) Import accepts and automatically synchronizes in case expression data there is not a 1:1 correspondence between the rownames of `obj` and the rownames of `res`, eg:

```
# import when randomly reorder res
se <- import(d, res[sample(nrow(res)),])
```

2) Import automatically restricts to common gene IDs of `obj` and `res`, eg:

```
# import when only the first 100 gene are provided with DE results
> se <- import(d, res[1:100,])
Restricting 'obj' and 'res' to 100 common gene IDs
It is recommended to provide DE results for all genes in 'obj'
```

It figured that this was actually not well documented in the first place so I added details here on what's expected for `obj` and `res`: https://github.com/lgeistlinger/EnrichmentBrowser/blob/fc25fd4cd813c41e2b0b36ce53b876d8a6469782/R/import.R#L26
