### ISSUE TITLE
Why is GAGE not an implemented method? 

### ISSUE THREAD

**Issue by tmms1** [lgeistlinger/EnrichmentBrowser#34]
Hello

Thank you for developing such a great tool.

I was wondering why GAGE is not implemented in this package? 

According to Web of Science (check on 16/09/2020), the paper outlining GAGE was cited 491 times. So it is a popular tool. 

With kind regards
Tim

**Comment by lgeistlinger** [comment]
Hi. Thanks for reaching out and your feedback.
There is no specific reason for not including GAGE other than time constraints, and GAGE would make a nice addition to the sbea methods currently supported, given that GAGE has a working R/Bioconductor implementation.
I also welcome pull requests that adapt calling of additional GSA methods via `sbea`.

**Comment by tmms1** [comment]
Thank for the quick response. 
I will keep the pull requests in mind.
