### ISSUE TITLE
KEGG gene set names are inconsiset

### ISSUE THREAD

**Issue by GabrielHoffman** [lgeistlinger/EnrichmentBrowser#36]
Hi, 
I realized that the gene set names for KEGG are different depending on how `getGenesets` is run.  Ideally, `gs.kegg_gsc` (below) would include the KEGG annotation like `gs.kegg_list` does.

```r
library(EnrichmentBrowser)
packageVersion("EnrichmentBrowser")
#> [1] '2.19.13'

gs.kegg_gsc = getGenesets(org = "hsa", db = "kegg", gene.id.type = 'SYMBOL', 
    return.type = "GeneSetCollection")
names(gs.kegg_gsc)[1:3]
#> [1] "hsa00010" "hsa00020" "hsa00030"

gs.kegg_list = getGenesets(org = "hsa", db = "kegg", gene.id.type = 'SYMBOL')
names(gs.kegg_list)[1:3]
#> [1] "hsa00010_Glycolysis_/_Gluconeogenesis"
#> [2] "hsa00020_Citrate_cycle_(TCA_cycle)"   
#> [3] "hsa00030_Pentose_phosphate_pathway"
```

Happy Thanksgiving
Gabriel

**Comment by lgeistlinger** [comment]
When represented as a simple list of character vectors, the `names` of a gene set are a composite string consisting of ID and title. That is mainly a result of the fact that a simple list is not compatible with the concept of metadata. That's not very clean (and always requires some string operations to extract the two parts), but is a result of the intuitive and simplified representation. 

The more structured representation in a `GeneSetCollection` allows annotation of metadata to a `GeneSet` (the `details` slot):

```
> kegg.gsc <- getGenesets(org = "hsa", db = "kegg", return.type = "GeneSetCollection")
> details(kegg.gsc[[1]])
setName: hsa00010 
geneIds: 10327, 124, ..., 9562 (total: 67)
geneIdType: EntrezId
collectionType: KEGG 
  ids: hsa00010 (1 total)
setIdentifier: Ludwigs-MacBook-Air.local:13524:Mon Nov 23 18:20:58 2020:61711
description: Glycolysis / Gluconeogenesis
organism: hsa
pubMedIds: 
urls: 
contributor: 
setVersion: 0.0.1
creationDate: 
```

which allows cleaner and separated annotation of gene set ID and the gene set title - and thus easier programmatic access to the two parts.

I found it often convenient for mapping purposes to simply refer by name (here gene set ID) to gene sets in a `GeneSetCollection`, and store the title in the short description slot.

(there are other options - you could also use the `setIdentifier` slot for storing the gene set ID) 

```
> titles <- sapply(kegg.gsc, description)
> titles
  [1] "Glycolysis / Gluconeogenesis"                                 
  [2] "Citrate cycle (TCA cycle)"                                    
  [3] "Pentose phosphate pathway"                                    
  [4] "Pentose and glucuronate interconversions"                     
  [5] "Fructose and mannose metabolism"                              
  [6] "Galactose metabolism"                                         
  [7] "Ascorbate and aldarate metabolism"                            
  [8] "Fatty acid biosynthesis"                                      
  [9] "Fatty acid elongation"                                        
 [10] "Fatty acid degradation"   
...                        
``` 

That means you could always overwrite the names 
```
titles <- gsub(" ", "_", titles)
names(kegg.gsc) <- paste(names(kegg.gsc), titles, sep = "_")
```

if you wanted them to look like what you get from a simple list output.

Happy Thanksgiving!

**Comment by GabrielHoffman** [comment]
This was exactly what I was looking for.  Thanks for pointing out the `details` function!
