### ISSUE TITLE
Compatibility with MSigDB 7.2

### ISSUE THREAD

**Issue by GabrielHoffman** [lgeistlinger/EnrichmentBrowser#37]
Hi, 
Now that MSigDB is available through `msigdbr`, it would be great to be able to load it with `EnrichmentBrowser::getGenesets`.  Here is the issue and a simple fix.

I would like to load the new category C8:
```r
library(EnrichmentBrowser)
library(GSEABase)
library(msigdbr)

# this category is present in msigdbr
unique(msigdbr_collections()$gs_cat)
#> [1] "C1" "C2" "C3" "C4" "C5" "C6" "C7" "C8" "H"

# But EnrichmentBrowser throws and error
getGenesets(org="hsa", db="msigdb", gene.id.type = "ENSEMBL", return.type='GeneSetCollection', cat="C8", subcat=NA)
#> Error in match.arg(cat): 'arg' should be one of "H", "C1", "C2", "C3", "C4", "C5", "C6", "C7"
```

The issue is that `.getMSigDb()` hard codes in the valid categories:
```r
#https://github.com/lgeistlinger/EnrichmentBrowser/blob/0e0286b8d85c48b31540d31272dcd228f88a2e15/R/getGenesets.R#L354
.getMSigDb <- function(org, gene.id.type, cache, return.type,
                        cat = c("H", paste0("C", 1:7)), 
                        subcat = NA)
```

Can you either add C8 as a valid category, or use `unique(msigdbr_collections()$gs_cat)` to let msigdbr dynamically define the valid categories?

Did you just move to Boston?  Congrats!

Gabriel

**Comment by lgeistlinger** [comment]
Hi Gabriel,

Thanks a lot for the heads up.

> or use unique(msigdbr_collections()$gs_cat) to let msigdbr dynamically define the valid categories?

Excellent suggestion - will do.

> Did you just move to Boston? Congrats!

Thanks! Yes, since beginning of this year joined the newly established Center for Computational Biomedicine at Harvard Medical School.

Happy New Year!
Ludwig

**Comment by lgeistlinger** [comment]
incorporated via b295985

```
> getGenesets(org="hsa", db="msigdb", gene.id.type = "ENSEMBL", return.type='GeneSetCollection', cat="C8")
GeneSetCollection
  names: M39017_FAN_EMBRYONIC_CTX_BIG_GROUPS_CAJAL_RETZIUS, M39018_FAN_EMBRYONIC_CTX_BIG_GROUPS_BRAIN_ENDOTHELIAL, ..., M39322_CUI_DEVELOPING_HEART_VALVAR_ENDOTHELIAL_CELL (302 total)
  unique identifiers: ENSG00000238098, ENSG00000099204, ..., ENSG00000143367 (13642 total)
  types in collection:
    geneIdType: ENSEMBLIdentifier (1 total)
    collectionType: BroadCollection (1 total)
```

thanks!
