### ISSUE TITLE
error with eaBrowse

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [lgeistlinger/EnrichmentBrowser#41]
Hi,
Thank you so much for this package!
But I encountered some error when I ran eaBrowse.
`go <- eaBrowse(sbea.res1, html.only = TRUE, out.dir='./GO_results')
Creating gene report ...
   Creating set view ...
Error in hclust(get_dist(submat, distance), method = method) :
There can be no NA/NaN/Inf(arg10) when calling external functions`
Please help me!

**Comment by lgeistlinger** [comment]
Hi I would need a bit more context to be able to comment on your issue.

1. an example that allows me to reproduce your error starting from a fresh R session - if that is difficult to create, an alternative would be to send me your `sbea.res1` object that you input to `eaBrowse` via email. You would then need to say `saveRDS(sbea.res1, file = "<filename>.rds")` where you would accordingly replace the file name.

**Comment by lgeistlinger** [comment]
2. Please also provide the output of typing `sessionInfo()` just before you execute the above command, so that I know which version of R, Bioconductor, and the EnrichmentBrowser package you are working with.

Thanks!

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
Thank you very much for your reply. I have sent the `sbea.res1` and the output of `sessionInfo()` to your email.

Thanks!

**Comment by lgeistlinger** [comment]
Thanks for sending over the additional information.
There was an issue with the heatmap function which is now fixed.

You can install the new version of the package directly from github via:

```
BiocManager::install("lgeistlinger/EnrichmentBrowser")
```

(you will need to also have the `remotes` package installed for that).

Hope that helps.

P.S.: I'd also recommend installing a recent version of R (there have been some major updates in R-4.0).

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
Thank you very much.
I reinstalled the package and everything goes well now.

Thanks!

**Comment by lgeistlinger** [comment]
Great - thanks for reporting back!
