### ISSUE TITLE
Vignette Conversation Request

### ISSUE THREAD

**Issue by Rohit-Satyam** [lgeistlinger/EnrichmentBrowser#43]
Hi,
I'm volunteering with Sweave2Rmd and we're trying to convert all Bioconductor Sweave vignettes into Rmd files. Would you be willing to accept a pull request converting "Seamless navigation through combined results of the set and network-based enrichment analysis" for the "EnrichmentBrowser package" from one of our volunteers? We'll take care of converting the file. We'll ask you to review and accept the pull request. You'll also need to bump the version number in your DESCRIPTION file so that the build machines will recognize that a new version is available.

I tried reaching out to you via email but I think it might have been tossed in spam. Either ways please leave a response here so that we can proceed. 

Thanks for your time.

**Comment by lgeistlinger** [comment]
Hi @Rohit-Satyam - I will be happy to accept a pull request if the conversion figures out to be satisfactory and without losses. Best, Ludwig

**Comment by Rohit-Satyam** [comment]
Thanks!!
