### ISSUE TITLE
getGenesets returns a list of empty named lists when calling mice KEGG genesets

### ISSUE THREAD

**Issue by OliveIsLazy** [lgeistlinger/EnrichmentBrowser#45]
On Monday (March 6th) I noticed an issue with the method call `EnrichmentBrowser::getGenesets(org="mmu", db="kegg")`, where it would return the named list of genesets, but the genesets were empty as denoted by the character(0) value. The latest day that I 100% know the method call worked was 27th February, one week prior. 

I have been calling `EnrichmentBrowser::getGenesets(org="mmu", db="kegg", cache=FALSE)` over the past week to see if this issue would resolve itself, but it's still returning empty lists as of time of writing. Interestingly, the MSiGDB-H and GO databases appear to be working for mice data with `cache=FALSE`.

Can someone help me with this issue?

**Comment by lgeistlinger** [comment]
Thanks for reporting this - this is due to a recent change in the KEGGREST package and this should be already fixed in the latest release version of the EnrichmentBrowser (v.2.28.1) which is available from Bioconductor. Let me know if the problem persists after installing the latest version of the package. Thanks!

**Comment by OliveIsLazy** [comment]
It did fix it! both with and without cache.


This thread will probably be closed, but in case anyone else stumbles across this problem:

I had version 2.26.0, and (probably) because I'm a linux user I couldn't update to version 2.28.1 for the life of me, even using `sudo R`, even after uninstalling then restarting then reinstalling with BiocManager::install("EnrichmentBrowser"), it'd just always be version 2.26.0.

I managed to get it to install the correct package version by uninstalling EnrichmentBrowser, downloading the current package (as a tar.gz file) from the bioconductor page, then going to the directory with that tar.gz download and running `R CMD INSTALL EnrichmentBrowser_2.28.1.tar.gz`

**Comment by OliveIsLazy** [comment]
I just double checked and the 348 KEGG genesets match those that I had archived from February 27th.
