### ISSUE TITLE
SPIA fix not correctly implemented in 2.10.3

### ISSUE THREAD

**Issue by Ju-Rien** [lgeistlinger/EnrichmentBrowser#5]
Hi, 

The latest version, 2.10.3, does not include the SPIA fix which was supposed to be include.

See in the following picture, in the `.spia` code, I highlighted the line where the fix should have been on the left and the line of the current package version on the right (running `sessionInfo()`):
![image](https://user-images.githubusercontent.com/33677828/41720173-3ba0086e-7530-11e8-8d60-43fdec21f07f.png)

The code should read: 
https://github.com/lgeistlinger/EnrichmentBrowser/blob/932977362e9d637cbfaf2adcbc907b78f2833f69/R/nbea.R#L348-L351

Thank you!

**Comment by lgeistlinger** [comment]
Seems as if the commit escaped the bioc builder and another version bump is required.

**Comment by lgeistlinger** [comment]
Fixed in 2.10.4, http://bioconductor.org/packages/EnrichmentBrowser
