### ISSUE TITLE
Annotation package not found using readSE

### ISSUE THREAD

**Issue by approximately-normal** [lgeistlinger/EnrichmentBrowser#9]
Hi Ludwig,

Please forgive me if this is a rookie mistake, but I've been scratching my head all morning. I'm trying to use readSE to read in my expression matrix as per the manual. However, the readSE command returns an error: 

> "Corresponding annotation package not found: .db
> Make sure that you have it installed."

As far as I can tell, there is no such package as ".db". I can't install it with "biocLite(".db")" in any case. I am running Bioconductor 3.7 on R 3.5.1. My operating system is Ubuntu 18.04.1. Here's the offending code:

```
#Playing with enrichment browser
source("https://bioconductor.org/biocLite.R")
biocLite("EnrichmentBrowser")
library(EnrichmentBrowser)

setwd("~/Documents/Honours/Analysis/31_07trials/Rproject")

cdat.file <- system.file("../prep_out/colData.tab", package="EnrichmentBrowser")

rowdata<-read.csv("../prep_out/gc_matrix.csv")
rowdata<-rowdata[1]
write.table(rowdata, file="../prep_out/rowData.tab", sep='\t', row.names=FALSE,col.names=F)
rdat.file <- system.file("../prep_out/rowData.tab", package="EnrichmentBrowser")

expdata<-read.csv("../prep_out/gc_matrix.csv")
write.table(expdata, file="../prep_out/gc_matrix.tab", sep='\t', row.names=FALSE,col.names=F)
exprs.file <- system.file("../prep_out/gc_matrix.tab", package="EnrichmentBrowser")

se <- readSE(exprs.file, cdat.file, rdat.file, data.type="rseq")
```

Here's the full output:

> #Playing with enrichment browser
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.7 (BiocInstaller 1.30.0), ?biocLite for help
> biocLite("EnrichmentBrowser")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
Installing package(s) ‘EnrichmentBrowser’
trying URL 'https://bioconductor.org/packages/3.7/bioc/src/contrib/EnrichmentBrowser_2.10.7.tar.gz'
Content type 'application/x-gzip' length 1254224 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

* installing *source* package ‘EnrichmentBrowser’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (EnrichmentBrowser)

The downloaded source packages are in
	‘/tmp/RtmpO1rSCS/downloaded_packages’
> library(EnrichmentBrowser)
> 
> setwd("~/Documents/Honours/Analysis/31_07trials/Rproject")
> 
> cdat.file <- system.file("../prep_out/colData.tab", package="EnrichmentBrowser")
> 
> rowdata<-read.csv("../prep_out/gc_matrix.csv")
> rowdata<-rowdata[1]
> write.table(rowdata, file="../prep_out/rowData.tab", sep='\t', row.names=FALSE,col.names=F)
> rdat.file <- system.file("../prep_out/rowData.tab", package="EnrichmentBrowser")
> 
> expdata<-read.csv("../prep_out/gc_matrix.csv")
> write.table(expdata, file="../prep_out/gc_matrix.tab", sep='\t', row.names=FALSE,col.names=F)
> exprs.file <- system.file("../prep_out/gc_matrix.tab", package="EnrichmentBrowser")
> 
> se <- readSE(exprs.file, cdat.file, rdat.file, data.type="rseq")
Corresponding annotation package not found: .db
Make sure that you have it installed.
Install it now? (y/n): y
Bioconductor version 3.7 (BiocInstaller 1.30.0), ?biocLite for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.1 (2018-07-02).
Installing package(s) ‘.db’
Loading required package: .db
Error in get(anno.pkg) : object '.db' not found
In addition: Warning messages:
1: package ‘.db’ is not available (for R version 3.5.1) 
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘.db’

Cheers,

Jefferson

**Comment by lgeistlinger** [comment]
```
> system.file("extdata/exprs.tab", package="EnrichmentBrowser")
"/Library/Frameworks/R.framework/Versions/3.5/Resources/devel/EnrichmentBrowser/extdata/exprs.tab"
```

links to the Installation directory of the package.

I think in your case you don't need `system.file`, but just want to say:

```
exprs.file <- "../prep_out/gc_matrix.tab"
cdat.file <- "../prep_out/colData.tab"
rdat.file <- "../prep_out/rowData.tab"
```  

Then 

```
se <- readSE(exprs.file, cdat.file, rdat.file, data.type="rseq")
```

should work?

**Comment by approximately-normal** [comment]
Thanks Ludwig! I misunderstood what the system.file function was used for, thinking extdata was a reference to the directory of the input files. It works like a charm now!
